-- 코드를 입력하세요
SELECT  TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR, COUNT(*) AS COUNT
from ANIMAL_OUTS
where TO_CHAR(DATETIME, 'HH24') between 09 and 19
GROUP BY TO_CHAR(DATETIME, 'HH24')
order by hour asc