-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(B.START_DATE, 'MM')) AS MONTH, A.CAR_ID, COUNT(A.CAR_ID) AS RECORDS
FROM (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE>=TO_DATE('2022-08', 'YYYY-MM')
         AND START_DATE<TO_DATE('2022-11', 'YYYY-MM')
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID)>4) A
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID= B.CAR_ID
WHERE START_DATE>=TO_DATE('2022-08', 'YYYY-MM')
         AND START_DATE<TO_DATE('2022-11', 'YYYY-MM')
GROUP BY A.CAR_ID, TO_NUMBER(TO_CHAR(B.START_DATE, 'MM'))
ORDER BY MONTH ASC, A.CAR_ID DESC;