WITH Filtered_Cars AS (
  SELECT CAR_ID
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
  WHERE START_DATE >= TO_DATE('2022-08', 'YYYY-MM')
    AND START_DATE < TO_DATE('2022-11', 'YYYY-MM')
  GROUP BY CAR_ID
  HAVING COUNT(CAR_ID) >= 5
)
SELECT TO_NUMBER(TO_CHAR(CR.START_DATE, 'MM')) AS MONTH, CR.CAR_ID, COUNT(CR.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CR
JOIN Filtered_Cars FC ON CR.CAR_ID = FC.CAR_ID
WHERE CR.START_DATE >= TO_DATE('2022-08', 'YYYY-MM')
  AND CR.START_DATE < TO_DATE('2022-11', 'YYYY-MM')
GROUP BY TO_NUMBER(TO_CHAR(CR.START_DATE, 'MM')), CR.CAR_ID
ORDER BY MONTH ASC, CR.CAR_ID DESC;
