-- SELECT CONCAT('/home/grep/src/', CONCAT(CONCAT(BOARD_ID,'/') ,CONCAT(FILE_ID, CONCAT(FILE_NAME, FILE_EXT) ))) AS FILE_PATH
-- FROM USED_GOODS_FILE NATURAL JOIN 
--     (SELECT BOARD_ID, VIEWS, DENSE_RANK() OVER (ORDER BY VIEWS DESC) AS RANK
--     FROM USED_GOODS_BOARD)
-- WHERE RANK=1
-- ORDER BY FILE_ID DESC;

SELECT CONCAT('/home/grep/src/', CONCAT(CONCAT(BOARD_ID,'/') ,CONCAT(FILE_ID, CONCAT(FILE_NAME, FILE_EXT) ))) AS FILE_PATH
FROM USED_GOODS_FILE NATURAL JOIN 
    (SELECT BOARD_ID
    FROM(SELECT BOARD_ID, VIEWS
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC)
    WHERE ROWNUM=1)
ORDER BY FILE_ID DESC;

